### ISSUE TITLE
anchor links for headings?

### ISSUE THREAD

**Issue by FlxVctr** [OII-SDP-2016/oii_how_to_learn_to_code#14]
Like e.g. this link: http://pandas.pydata.org/pandas-docs/stable/cookbook.html#building-criteria

@cuducos: Is that easily doable?

**Comment by cuducos** [comment]
Every heading has an `id` attribute with a _slug_ version of the title, that's added automatically. 

So you can just use the URL + `#` + the slug for the title.

For example:

```
https://oii-sdp-2016.github.io/how-to-learn-to-code/#installing-python-on-your-computer
```

Does that help?

**Comment by FlxVctr** [comment]
Hm, we could just add this as a link to the headings then.

**Comment by FlxVctr** [comment]
What I want to do is to have some kind of Table of contents so that you can easily proceed from where you've stopped last time.
