### ISSUE TITLE
open links in new tab?

### ISSUE THREAD

**Issue by FlxVctr** [OII-SDP-2016/oii_how_to_learn_to_code#18]
Maybe it's easier to keep the guide open while doing the courses that way. (Yes, you can do it yourself, but somehow that would be the expected behaviour of the site for me.)

**Comment by cuducos** [comment]
AFAIK markdown does not offer this possibility (I mean, the possibility of adding a `target` HTML attribute to links). I can try to code a JavaScript to do that with all external links… it's a bit hacky but it might worth it in the name of UX… gonna send a PR soon.
