### ISSUE TITLE
paragraph about data analysis

### ISSUE THREAD

**Issue by FlxVctr** [OII-SDP-2016/oii_how_to_learn_to_code#2]
Should contain a resource to a course with pandas, e.g. the course on https://www.datacamp.com/

**Comment by cuducos** [comment]
I nerver know if DataCamp is a free or paid resource… I was looking for alternatives:
- [This one](http://scipy.github.io/old-wiki/pages/Tentative_NumPy_Tutorial.html) seems a good intro to NumPy;
- [this other one](http://www.scipy-lectures.org) is quite lengthy, but covers a lot of stuff such as Matplotlib, SciPy, Scikit…
- and [this resource from Harvard's Data Science Course](https://www.quora.com/How-do-I-learn-data-mining-Is-this-Harvard-course-cs109-still-valid-with-recent-developments) looks good and use Pandas.

I think @FlxVctr is way more experienced than I am to make a decision here… what do you think?

**Comment by FlxVctr** [comment]
The introductory course on datacamp is free and pretty neat to give you the basics, so I'd include it just as a starter, then you can go on to more advanced stuff.

**Comment by cuducos** [comment]
Does it has a big overlap with Codecademy's Python course (in the sense of intro do Python)? If it doesn't lets add DataCamp and if you think any of these links above are valuable, we add them to the extras at the bottom of the page.

**Comment by FlxVctr** [comment]
Yeah, ok, you're right. The relevant course actually is in the paid section … They have a student plan for $9 a month (https://www.datacamp.com/enroll-student), but I'm hesitant to recommend paid ressources (even though I like this one and it's one of the best ressources for R, which would be good for Megs and @jaruizso's part).

**Comment by cuducos** [comment]
I like your argument (_it's one of the best ressources for R_). I would add it to the page with a highlight that it is a paid course (pretty good one though) — and meanwhile we try to find some free alternative.

**Comment by FlxVctr** [comment]
Actually the 10 minutes quick start in the pandas documentation is not that bad: http://pandas.pydata.org/pandas-docs/stable/10min.html
